# Generated by Django 5.0.6 on 2024-08-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_review_createat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='createAt',
            new_name='createdAt',
        ),
    ]
